#pragma once

#define PROJ_SCREENMODE MODE15
#define PROJ_FPS 60

#define PROJ_HIGH_RAM HIGH_RAM_MUSIC
#define PROJ_ENABLE_SOUND 1
#define PROJ_ENABLE_SFX
#define PROJ_ENABLE_SD_MUSIC
#define PROJ_AUD_FREQ 16000
#define PROJ_STREAM_LOOP 0

